# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fca8abbe5f4b0a52fced8237dd3e0f5fdc9851a6e8b58b3b0a02b2946f9e04c48f077ae33f1d5d2a2503d7aeb1d92f832c66480453e7a0fd12c80ab6bc559545

test:
  secret_key_base: 338763ebd85758ecbe34dcda6e793ab71bbe399a9e6c7a178dd4f372440ed0eef86b031e5c1f5674bfcfb12119d5a5186326b98bd94c8c4256d9950d26eecd78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
